# Generated by Django 5.2.12 on 2026-03-16 16:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registrationotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/defaultProfile.png', upload_to=accounts.models.user_profile_path),
        ),
    ]
